---
title: "Parametric Bootstrap (The Ornstein–Uhlenbeck Model)"
author: "Ivan Jacob Agaloos Pesigan"
date: "2025-01-14"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @RCoreTeam-2024
  @Ou-Hunter-Chow-2019
  @Chow-Losardo-Park-etal-2023
  @Uhlenbeck-Ornstein-1930
  @Chow-Ho-Hamaker-etal-2010
  @Deboeck-Preacher-2015
  @Oravecz-Tuerlinckx-Vandekerckhove-2011
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Parametric Bootstrap (The Ornstein–Uhlenbeck Model)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





## Model

The measurement model is given by
\begin{equation}
  \mathbf{y}_{i, t}
  =
  \boldsymbol{\nu}
  +
  \boldsymbol{\Lambda}
  \boldsymbol{\eta}_{i, t}
  +
  \boldsymbol{\varepsilon}_{i, t},
  \quad
  \mathrm{with}
  \quad
  \boldsymbol{\varepsilon}_{i, t}
  \sim
  \mathcal{N}
  \left(
  \mathbf{0},
  \boldsymbol{\Theta}
  \right)
\end{equation}
where
$\mathbf{y}_{i, t}$,
$\boldsymbol{\eta}_{i, t}$,
and
$\boldsymbol{\varepsilon}_{i, t}$
are random variables
and
$\boldsymbol{\nu}$,
$\boldsymbol{\Lambda}$,
and
$\boldsymbol{\Theta}$
are model parameters.
$\mathbf{y}_{i, t}$
represents a vector of observed random variables,
$\boldsymbol{\eta}_{i, t}$
a vector of latent random variables,
and
$\boldsymbol{\varepsilon}_{i, t}$
a vector of random measurement errors,
at time $t$ and individual $i$.
$\boldsymbol{\nu}$
denotes a vector of intercepts,
$\boldsymbol{\Lambda}$
a matrix of factor loadings,
and
$\boldsymbol{\Theta}$
the covariance matrix of
$\boldsymbol{\varepsilon}$.

An alternative representation of the measurement error
is given by
\begin{equation}
  \boldsymbol{\varepsilon}_{i, t}
  =
  \boldsymbol{\Theta}^{\frac{1}{2}}
  \mathbf{z}_{i, t},
  \quad
  \mathrm{with}
  \quad
  \mathbf{z}_{i, t}
  \sim
  \mathcal{N}
  \left(
  \mathbf{0},
  \mathbf{I}
  \right)
\end{equation}
where
$\mathbf{z}_{i, t}$ is a vector of
independent standard normal random variables and
$\left( \boldsymbol{\Theta}^{\frac{1}{2}} \right) \left( \boldsymbol{\Theta}^{\frac{1}{2}} \right)^{\prime} = \boldsymbol{\Theta}$ .

The dynamic structure is given by
\begin{equation}
  \mathrm{d} \boldsymbol{\eta}_{i, t}
  =
  \boldsymbol{\Phi}
  \left(
  \boldsymbol{\eta}_{i, t}
  -
  \boldsymbol{\mu}
  \right)
  \mathrm{d}t
  +
  \boldsymbol{\Sigma}^{\frac{1}{2}}
  \mathrm{d}
  \mathbf{W}_{i, t}
\end{equation}
where
$\boldsymbol{\mu}$
is the long-term mean or equilibrium level,
$\boldsymbol{\Phi}$
is the rate of mean reversion,
determining how quickly the variable returns to its mean,
$\boldsymbol{\Sigma}$
is the matrix of volatility
or randomness in the process, and
$\mathrm{d}\boldsymbol{W}$
is a Wiener process or Brownian motion,
which represents random fluctuations.

## Parameters

### Notation

Let $t = 1000$ be the number of time points and $n = 5$ be the number of individuals.

Let the measurement model intecept vector $\boldsymbol{\nu}$ be given by

\begin{equation}
\boldsymbol{\nu}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
  0 \\
\end{array}
\right) .
\end{equation}

Let the factor loadings matrix $\boldsymbol{\Lambda}$ be given by

\begin{equation}
\boldsymbol{\Lambda}
=
\left(
\begin{array}{ccc}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1 \\
\end{array}
\right) .
\end{equation}

Let the measurement error covariance matrix $\boldsymbol{\Theta}$ be given by

\begin{equation}
\boldsymbol{\Theta}
=
\left(
\begin{array}{ccc}
  0.2 & 0 & 0 \\
  0 & 0.2 & 0 \\
  0 & 0 & 0.2 \\
\end{array}
\right) .
\end{equation}

Let the initial condition
$\boldsymbol{\eta}_{0}$
be given by

\begin{equation}
\boldsymbol{\eta}_{0} \sim \mathcal{N} \left( \boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}, \boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0} \right)
\end{equation}

\begin{equation}
\boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
  0 \\
\end{array}
\right)
\end{equation}

\begin{equation}
\boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{ccc}
  1 & 0.2 & 0.2 \\
  0.2 & 1 & 0.2 \\
  0.2 & 0.2 & 1 \\
\end{array}
\right) .
\end{equation}

Let the long-term mean vector $\boldsymbol{\mu}$ be given by

\begin{equation}
\boldsymbol{\mu}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
  0 \\
\end{array}
\right) .
\end{equation}

Let the rate of mean reversion matrix $\boldsymbol{\Phi}$ be given by

\begin{equation}
\boldsymbol{\Phi}
=
\left(
\begin{array}{ccc}
  -0.357 & 0 & 0 \\
  0.771 & -0.511 & 0 \\
  -0.45 & 0.729 & -0.693 \\
\end{array}
\right) .
\end{equation}

Let the dynamic process noise covariance matrix $\boldsymbol{\Sigma}$ be given by

\begin{equation}
\boldsymbol{\Sigma}
=
\left(
\begin{array}{ccc}
  0.2445556 & 0.0220159 & -0.0500476 \\
  0.0220159 & 0.070678 & 0.0153946 \\
  -0.0500476 & 0.0153946 & 0.0755306 \\
\end{array}
\right) .
\end{equation}

Let $\Delta t = 0.1$.

### R Function Arguments


``` r
n
#> [1] 5
time
#> [1] 1000
delta_t
#> [1] 0.1
mu0
#> [1] 0 0 0
sigma0
#>      [,1] [,2] [,3]
#> [1,]  1.0  0.2  0.2
#> [2,]  0.2  1.0  0.2
#> [3,]  0.2  0.2  1.0
sigma0_l # sigma0_l <- t(chol(sigma0))
#>      [,1]      [,2]      [,3]
#> [1,]  1.0 0.0000000 0.0000000
#> [2,]  0.2 0.9797959 0.0000000
#> [3,]  0.2 0.1632993 0.9660918
mu
#> [1] 0 0 0
phi
#>        [,1]   [,2]   [,3]
#> [1,] -0.357  0.000  0.000
#> [2,]  0.771 -0.511  0.000
#> [3,] -0.450  0.729 -0.693
sigma
#>             [,1]       [,2]        [,3]
#> [1,]  0.24455556 0.02201587 -0.05004762
#> [2,]  0.02201587 0.07067800  0.01539456
#> [3,] -0.05004762 0.01539456  0.07553061
sigma_l # sigma_l <- t(chol(sigma))
#>             [,1]      [,2]     [,3]
#> [1,]  0.49452559 0.0000000 0.000000
#> [2,]  0.04451917 0.2620993 0.000000
#> [3,] -0.10120330 0.0759256 0.243975
nu
#> [1] 0 0 0
lambda
#>      [,1] [,2] [,3]
#> [1,]    1    0    0
#> [2,]    0    1    0
#> [3,]    0    0    1
theta
#>      [,1] [,2] [,3]
#> [1,]  0.2  0.0  0.0
#> [2,]  0.0  0.2  0.0
#> [3,]  0.0  0.0  0.2
theta_l # theta_l <- t(chol(theta))
#>           [,1]      [,2]      [,3]
#> [1,] 0.4472136 0.0000000 0.0000000
#> [2,] 0.0000000 0.4472136 0.0000000
#> [3,] 0.0000000 0.0000000 0.4472136
```

### Parametric Bootstrap


``` r
R <- 1000L # use at least 1000 in actual research
path <- getwd()
prefix <- "ou"
```

We use the `PBSSMOUFixed` function from the `simStateSpace` package to perform parametric bootstraping using the parameters described above.
The argument `R` specifies the number of bootstrap replications.
The generated data and model estimates are stored in `path` using the specified `prefix` for the file names.
The `ncores = parallel::detectCores()` argument instructs the function to use all available CPU cores in the system.

> **_NOTE:_**  Fitting the Ornstein–Uhlenbeck model multiple times is computationally intensive. 


``` r
library(simStateSpace)
pb <- PBSSMOUFixed(
  R = R,
  path = path,
  prefix = prefix,
  n = n,
  time = time,
  delta_t = delta_t,
  mu0 = mu0,
  sigma0_l = sigma0_l,
  mu = mu,
  phi = phi,
  sigma_l = sigma_l,
  nu = nu,
  lambda = lambda,
  theta_l = theta_l,
  ncores = parallel::detectCores(),
  seed = 42
)
summary(pb)
#> Call:
#> PBSSMOUFixed(R = R, path = path, prefix = prefix, n = n, time = time, 
#>     delta_t = delta_t, mu0 = mu0, sigma0_l = sigma0_l, mu = mu, 
#>     phi = phi, sigma_l = sigma_l, nu = nu, lambda = lambda, theta_l = theta_l, 
#>     ncores = parallel::detectCores(), seed = 42)
#> 
#> Parametric bootstrap confidence intervals.
#> type = "pc"
#>                est     se    R    2.5%   97.5%
#> phi_1_1    -0.3570 0.1699 1000 -0.7001 -0.0508
#> phi_2_1     0.7710 0.1034 1000  0.5816  0.9878
#> phi_3_1    -0.4500 0.1044 1000 -0.6636 -0.2538
#> phi_1_2     0.0000 0.1466 1000 -0.2746  0.2954
#> phi_2_2    -0.5110 0.0917 1000 -0.7021 -0.3440
#> phi_3_2     0.7290 0.0933 1000  0.5576  0.9286
#> phi_1_3     0.0000 0.1086 1000 -0.2234  0.1977
#> phi_2_3     0.0000 0.0685 1000 -0.1312  0.1446
#> phi_3_3    -0.6930 0.0726 1000 -0.8544 -0.5643
#> sigma_1_1   0.2446 0.0313 1000  0.1909  0.3122
#> sigma_2_1   0.0220 0.0122 1000 -0.0015  0.0444
#> sigma_3_1  -0.0500 0.0124 1000 -0.0752 -0.0258
#> sigma_2_2   0.0707 0.0091 1000  0.0537  0.0892
#> sigma_3_2   0.0154 0.0063 1000  0.0030  0.0277
#> sigma_3_3   0.0755 0.0098 1000  0.0571  0.0948
#> theta_1_1   0.2000 0.0053 1000  0.1901  0.2109
#> theta_2_2   0.2000 0.0045 1000  0.1912  0.2091
#> theta_3_3   0.2000 0.0045 1000  0.1913  0.2088
#> mu0_1_1     0.0000 0.4539 1000 -0.9004  0.8934
#> mu0_2_1     0.0000 0.4624 1000 -0.9453  0.9216
#> mu0_3_1     0.0000 0.4481 1000 -0.8804  0.8994
#> sigma0_1_1  1.0000 0.5817 1000  0.0497  2.2765
#> sigma0_2_1  0.2000 0.4383 1000 -0.5675  1.1787
#> sigma0_3_1  0.2000 0.4101 1000 -0.5626  1.1054
#> sigma0_2_2  1.0000 0.6239 1000  0.0550  2.3037
#> sigma0_3_2  0.2000 0.4454 1000 -0.6436  1.1700
#> sigma0_3_3  1.0000 0.5942 1000  0.0691  2.3123
summary(pb, type = "bc")
#> Call:
#> PBSSMOUFixed(R = R, path = path, prefix = prefix, n = n, time = time, 
#>     delta_t = delta_t, mu0 = mu0, sigma0_l = sigma0_l, mu = mu, 
#>     phi = phi, sigma_l = sigma_l, nu = nu, lambda = lambda, theta_l = theta_l, 
#>     ncores = parallel::detectCores(), seed = 42)
#> 
#> Parametric bootstrap confidence intervals.
#> type = "bc"
#>                est     se    R    2.5%   97.5%
#> phi_1_1    -0.3570 0.1699 1000 -0.6815 -0.0366
#> phi_2_1     0.7710 0.1034 1000  0.5740  0.9761
#> phi_3_1    -0.4500 0.1044 1000 -0.6558 -0.2455
#> phi_1_2     0.0000 0.1466 1000 -0.2932  0.2725
#> phi_2_2    -0.5110 0.0917 1000 -0.6950 -0.3359
#> phi_3_2     0.7290 0.0933 1000  0.5411  0.9036
#> phi_1_3     0.0000 0.1086 1000 -0.1944  0.2169
#> phi_2_3     0.0000 0.0685 1000 -0.1328  0.1416
#> phi_3_3    -0.6930 0.0726 1000 -0.8415 -0.5562
#> sigma_1_1   0.2446 0.0313 1000  0.1898  0.3095
#> sigma_2_1   0.0220 0.0122 1000 -0.0014  0.0445
#> sigma_3_1  -0.0500 0.0124 1000 -0.0758 -0.0266
#> sigma_2_2   0.0707 0.0091 1000  0.0538  0.0894
#> sigma_3_2   0.0154 0.0063 1000  0.0033  0.0278
#> sigma_3_3   0.0755 0.0098 1000  0.0574  0.0952
#> theta_1_1   0.2000 0.0053 1000  0.1902  0.2113
#> theta_2_2   0.2000 0.0045 1000  0.1911  0.2091
#> theta_3_3   0.2000 0.0045 1000  0.1912  0.2083
#> mu0_1_1     0.0000 0.4539 1000 -0.8903  0.9166
#> mu0_2_1     0.0000 0.4624 1000 -0.9409  0.9229
#> mu0_3_1     0.0000 0.4481 1000 -0.8937  0.8755
#> sigma0_1_1  1.0000 0.5817 1000  0.2902  3.2078
#> sigma0_2_1  0.2000 0.4383 1000 -0.4340  1.4370
#> sigma0_3_1  0.2000 0.4101 1000 -0.3913  1.3177
#> sigma0_2_2  1.0000 0.6239 1000  0.2921  5.0804
#> sigma0_3_2  0.2000 0.4454 1000 -0.4393  1.4506
#> sigma0_3_3  1.0000 0.5942 1000  0.3007  3.6202
```

## References


