---
title: "Parametric Bootstrap (The Vector Autoregressive Model)"
author: "Ivan Jacob Agaloos Pesigan"
date: "2025-01-15"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @RCoreTeam-2024
  @Ou-Hunter-Chow-2019
  @Chow-Ho-Hamaker-etal-2010
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Parametric Bootstrap (The Vector Autoregressive Model)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





## Model

The measurement model is given by
\begin{equation}
  \mathbf{y}_{i, t}
  =
  \boldsymbol{\eta}_{i, t}
\end{equation}
where $\mathbf{y}_{i, t}$
represents a vector of observed variables
and $\boldsymbol{\eta}_{i, t}$
a vector of latent variables
for individual $i$ and time $t$.
Since the observed and latent variables are equal,
we only generate data
from the dynamic structure.

The dynamic structure is given by
\begin{equation}
  \boldsymbol{\eta}_{i, t}
  =
  \boldsymbol{\alpha}
  +
  \boldsymbol{\beta}
  \boldsymbol{\eta}_{i, t - 1}
  +
  \boldsymbol{\zeta}_{i, t},
  \quad
  \mathrm{with}
  \quad
  \boldsymbol{\zeta}_{i, t}
  \sim
  \mathcal{N}
  \left(
  \mathbf{0},
  \boldsymbol{\Psi}
  \right)
\end{equation}
where
$\boldsymbol{\eta}_{i, t}$,
$\boldsymbol{\eta}_{i, t - 1}$,
and
$\boldsymbol{\zeta}_{i, t}$
are random variables,
and
$\boldsymbol{\alpha}$,
$\boldsymbol{\beta}$,
and
$\boldsymbol{\Psi}$
are model parameters.
Here,
$\boldsymbol{\eta}_{i, t}$
is a vector of latent variables
at time $t$ and individual $i$,
$\boldsymbol{\eta}_{i, t - 1}$
represents a vector of latent variables
at time $t - 1$ and individual $i$,
and
$\boldsymbol{\zeta}_{i, t}$
represents a vector of dynamic noise
at time $t$ and individual $i$.
$\boldsymbol{\alpha}$
denotes a vector of intercepts,
$\boldsymbol{\beta}$
a matrix of autoregression
and cross regression coefficients,
and
$\boldsymbol{\Psi}$
the covariance matrix of
$\boldsymbol{\zeta}_{i, t}$.

An alternative representation of the dynamic noise
is given by
\begin{equation}
  \boldsymbol{\zeta}_{i, t}
  =
  \boldsymbol{\Psi}^{\frac{1}{2}}
  \mathbf{z}_{i, t},
  \quad
  \mathrm{with}
  \quad
  \mathbf{z}_{i, t}
  \sim
  \mathcal{N}
  \left(
  \mathbf{0},
  \mathbf{I}
  \right)
\end{equation}
where
$\left( \boldsymbol{\Psi}^{\frac{1}{2}} \right) \left( \boldsymbol{\Psi}^{\frac{1}{2}} \right)^{\prime} = \boldsymbol{\Psi}$ .

## Parameters

### Notation

Let $t = 1000$ be the number of time points and $n = 5$ be the number of individuals.

Let the initial condition
$\boldsymbol{\eta}_{0}$
be given by

\begin{equation}
\boldsymbol{\eta}_{0} \sim \mathcal{N} \left( \boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}, \boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0} \right)
\end{equation}

\begin{equation}
\boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
  0 \\
\end{array}
\right)
\end{equation}

\begin{equation}
\boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{ccc}
  1 & 0.2 & 0.2 \\
  0.2 & 1 & 0.2 \\
  0.2 & 0.2 & 1 \\
\end{array}
\right) .
\end{equation}

Let the constant vector $\boldsymbol{\alpha}$ be given by

\begin{equation}
\boldsymbol{\alpha}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
  0 \\
\end{array}
\right) .
\end{equation}

Let the transition matrix $\boldsymbol{\beta}$ be given by

\begin{equation}
\boldsymbol{\beta}
=
\left(
\begin{array}{ccc}
  0.7 & 0 & 0 \\
  0.5 & 0.6 & 0 \\
  -0.1 & 0.4 & 0.5 \\
\end{array}
\right) .
\end{equation}

Let the dynamic process noise $\boldsymbol{\Psi}$ be given by

\begin{equation}
\boldsymbol{\Psi}
=
\left(
\begin{array}{ccc}
  0.1 & 0 & 0 \\
  0 & 0.1 & 0 \\
  0 & 0 & 0.1 \\
\end{array}
\right) .
\end{equation}

### R Function Arguments


``` r
n
#> [1] 5
time
#> [1] 1000
mu0
#> [1] 0 0 0
sigma0
#>      [,1] [,2] [,3]
#> [1,]  1.0  0.2  0.2
#> [2,]  0.2  1.0  0.2
#> [3,]  0.2  0.2  1.0
sigma0_l # sigma0_l <- t(chol(sigma0))
#>      [,1]      [,2]      [,3]
#> [1,]  1.0 0.0000000 0.0000000
#> [2,]  0.2 0.9797959 0.0000000
#> [3,]  0.2 0.1632993 0.9660918
alpha
#> [1] 0 0 0
beta
#>      [,1] [,2] [,3]
#> [1,]  0.7  0.0  0.0
#> [2,]  0.5  0.6  0.0
#> [3,] -0.1  0.4  0.5
psi
#>      [,1] [,2] [,3]
#> [1,]  0.1  0.0  0.0
#> [2,]  0.0  0.1  0.0
#> [3,]  0.0  0.0  0.1
psi_l # psi_l <- t(chol(psi))
#>           [,1]      [,2]      [,3]
#> [1,] 0.3162278 0.0000000 0.0000000
#> [2,] 0.0000000 0.3162278 0.0000000
#> [3,] 0.0000000 0.0000000 0.3162278
```

### Parametric Bootstrap


``` r
R <- 1000L # use at least 1000 in actual research
path <- getwd()
prefix <- "var"
```

We use the `PBSSMVARFixed` function from the `simStateSpace` package to perform parametric bootstraping using the parameters described above.
The argument `R` specifies the number of bootstrap replications.
The generated data and model estimates are stored in `path` using the specified `prefix` for the file names.
The `ncores = parallel::detectCores()` argument instructs the function to use all available CPU cores in the system.

> **_NOTE:_**  Fitting the VAR model multiple times is computationally intensive. 


``` r
library(simStateSpace)
pb <- PBSSMVARFixed(
  R = R,
  path = path,
  prefix = prefix,
  n = n,
  time = time,
  mu0 = mu0,
  sigma0_l = sigma0_l,
  alpha = alpha,
  beta = beta,
  psi_l = psi_l,
  ncores = parallel::detectCores(),
  seed = 42
)
summary(pb)
#> Call:
#> PBSSMVARFixed(R = R, path = path, prefix = prefix, n = n, time = time, 
#>     mu0 = mu0, sigma0_l = sigma0_l, alpha = alpha, beta = beta, 
#>     psi_l = psi_l, ncores = parallel::detectCores(), seed = 42)
#> 
#> Parametric bootstrap confidence intervals.
#> type = "pc"
#>             est     se    R    2.5%   97.5%
#> beta_1_1    0.7 0.0111 1000  0.6770  0.7220
#> beta_2_1    0.5 0.0121 1000  0.4774  0.5242
#> beta_3_1   -0.1 0.0115 1000 -0.1232 -0.0778
#> beta_1_2    0.0 0.0092 1000 -0.0180  0.0174
#> beta_2_2    0.6 0.0097 1000  0.5796  0.6180
#> beta_3_2    0.4 0.0097 1000  0.3813  0.4182
#> beta_1_3    0.0 0.0096 1000 -0.0190  0.0185
#> beta_2_3    0.0 0.0097 1000 -0.0182  0.0194
#> beta_3_3    0.5 0.0099 1000  0.4798  0.5186
#> psi_1_1     0.1 0.0020 1000  0.0962  0.1038
#> psi_2_2     0.1 0.0021 1000  0.0958  0.1038
#> psi_3_3     0.1 0.0021 1000  0.0960  0.1043
#> mu0_1_1     0.0 0.4489 1000 -0.8529  0.8740
#> mu0_2_1     0.0 0.4457 1000 -0.7936  0.8979
#> mu0_3_1     0.0 0.4357 1000 -0.8548  0.8466
#> sigma0_1_1  1.0 0.6131 1000  0.0948  2.3627
#> sigma0_2_1  0.2 0.4146 1000 -0.5173  1.1095
#> sigma0_3_1  0.2 0.4179 1000 -0.5867  1.1012
#> sigma0_2_2  1.0 0.5798 1000  0.0847  2.2834
#> sigma0_3_2  0.2 0.4124 1000 -0.5218  1.0941
#> sigma0_3_3  1.0 0.5642 1000  0.0936  2.1704
summary(pb, type = "bc")
#> Call:
#> PBSSMVARFixed(R = R, path = path, prefix = prefix, n = n, time = time, 
#>     mu0 = mu0, sigma0_l = sigma0_l, alpha = alpha, beta = beta, 
#>     psi_l = psi_l, ncores = parallel::detectCores(), seed = 42)
#> 
#> Parametric bootstrap confidence intervals.
#> type = "bc"
#>             est     se    R    2.5%   97.5%
#> beta_1_1    0.7 0.0111 1000  0.6770  0.7220
#> beta_2_1    0.5 0.0121 1000  0.4775  0.5245
#> beta_3_1   -0.1 0.0115 1000 -0.1238 -0.0784
#> beta_1_2    0.0 0.0092 1000 -0.0179  0.0177
#> beta_2_2    0.6 0.0097 1000  0.5796  0.6179
#> beta_3_2    0.4 0.0097 1000  0.3817  0.4185
#> beta_1_3    0.0 0.0096 1000 -0.0197  0.0179
#> beta_2_3    0.0 0.0097 1000 -0.0192  0.0190
#> beta_3_3    0.5 0.0099 1000  0.4805  0.5187
#> psi_1_1     0.1 0.0020 1000  0.0963  0.1041
#> psi_2_2     0.1 0.0021 1000  0.0963  0.1048
#> psi_3_3     0.1 0.0021 1000  0.0961  0.1043
#> mu0_1_1     0.0 0.4489 1000 -0.8537  0.8663
#> mu0_2_1     0.0 0.4457 1000 -0.8403  0.8489
#> mu0_3_1     0.0 0.4357 1000 -0.8546  0.8490
#> sigma0_1_1  1.0 0.6131 1000  0.3125  3.9395
#> sigma0_2_1  0.2 0.4146 1000 -0.3912  1.4120
#> sigma0_3_1  0.2 0.4179 1000 -0.4263  1.2495
#> sigma0_2_2  1.0 0.5798 1000  0.3372  4.1256
#> sigma0_3_2  0.2 0.4124 1000 -0.3187  1.4554
#> sigma0_3_3  1.0 0.5642 1000  0.3006  3.6517
```

## References


