---
title: "The Vector Autoregressive Model"
author: "Ivan Jacob Agaloos Pesigan"
date: "2023-11-18"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @RCoreTeam-2023
  @Shumway-Stoffer-2017
  @Ou-Hunter-Chow-2019
  @Chow-Ho-Hamaker-etal-2010
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{The Vector Autoregressive Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Model

The measurement model is given by

\begin{equation}
  \mathbf{y}_{i, t}
  =
  \boldsymbol{\eta}_{i, t} .
\end{equation}

The dynamic structure is given by

\begin{equation}
  \boldsymbol{\eta}_{i, t}
  =
  \boldsymbol{\alpha}
  +
  \boldsymbol{\beta}
  \boldsymbol{\eta}_{i, t - 1}
  +
  \boldsymbol{\zeta}_{i, t}
  \quad
  \mathrm{with}
  \quad
  \boldsymbol{\zeta}_{i, t}
  \sim
  \mathcal{N}
  \left(
  \mathbf{0},
  \boldsymbol{\Psi}
  \right)
\end{equation}

where $\boldsymbol{\eta}_{i, t}$, $\boldsymbol{\eta}_{i, t - 1}$,
and $\boldsymbol{\zeta}_{i, t}$ are random variables
and $\boldsymbol{\alpha}$, $\boldsymbol{\beta}$,
and $\boldsymbol{\Psi}$ are model parameters.
$\boldsymbol{\eta}_{i, t}$ is a vector of latent variables
at time $t$ and individual $i$, $\boldsymbol{\eta}_{i, t - 1}$
is a vector of latent variables at
$t - 1$ and individual $i$,
and $\boldsymbol{\zeta}_{i, t}$ is a vector of dynamic noise
at time $t$ and individual $i$,
while $\boldsymbol{\alpha}$
is a vector of intercepts,
$\boldsymbol{\beta}$ is a matrix of autoregression
and cross regression coefficients,
and $\boldsymbol{\Psi}$ is the covariance matrix of
$\boldsymbol{\zeta}_{i, t}$.

## Data Generation

### Notation



Let $t = 1000$ be the number of time points and $n = 20$ be the number of individuals.

Let the initial condition
$\boldsymbol{\eta}_{0}$
be given by

\begin{equation}
\boldsymbol{\eta}_{0} \sim \mathcal{N} \left( \boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}, \boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0} \right)
\end{equation}

\begin{equation}
\boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
  0 \\
\end{array}
\right)
\end{equation}

\begin{equation}
\boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{ccc}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1 \\
\end{array}
\right) .
\end{equation}

Let the constant vector $\boldsymbol{\alpha}$ be given by

\begin{equation}
\boldsymbol{\alpha}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
  0 \\
\end{array}
\right) .
\end{equation}

Let the transition matrix $\boldsymbol{\beta}$ be given by

\begin{equation}
\boldsymbol{\beta}
=
\left(
\begin{array}{ccc}
  0.7 & 0 & 0 \\
  0.5 & 0.6 & 0 \\
  -0.1 & 0.4 & 0.5 \\
\end{array}
\right) .
\end{equation}

Let the dynamic process noise $\boldsymbol{\Psi}$ be given by

\begin{equation}
\boldsymbol{\Psi}
=
\left(
\begin{array}{ccc}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1 \\
\end{array}
\right) .
\end{equation}

### R Function Arguments


```r
n
```

```
## [1] 20
```

```r
time
```

```
## [1] 1000
```

```r
mu0
```

```
## [1] 0 0 0
```

```r
sigma0
```

```
##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]    0    1    0
## [3,]    0    0    1
```

```r
alpha
```

```
## [1] 0 0 0
```

```r
beta
```

```
##      [,1] [,2] [,3]
## [1,]  0.7  0.0  0.0
## [2,]  0.5  0.6  0.0
## [3,] -0.1  0.4  0.5
```

```r
psi
```

```
##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]    0    1    0
## [3,]    0    0    1
```

### Using the SimSSMVARFixed Function to Simulate Data


```r
library(simStateSpace)
data <- Sim2Matrix(
  SimSSMVARFixed(
    n = n,
    mu0 = mu0,
    sigma0_sqrt = chol(sigma0),
    alpha = alpha,
    beta = beta,
    psi_sqrt = chol(psi),
    time = time,
    burn_in = 0
  )
)
head(data)
```

```
##               y1         y2        y3 time id
## [1,] -0.53150173  0.8212527 2.2174497    1  1
## [2,]  0.03280741 -0.3981712 2.4785526    2  1
## [3,] -0.31722163  1.5413967 1.1638121    3  1
## [4,] -0.28222201  1.4683295 0.1377762    4  1
## [5,] -1.04463827  0.7687173 0.4667933    5  1
## [6,] -0.92475541  1.1649958 1.2460595    6  1
```

## Model Fitting

### Prepare Data


```r
dynr_data <- dynr::dynr.data(
  data = data,
  id = "id",
  time = "time",
  observed = c("y1", "y2", "y3")
)
```

### Prepare Initial Condition


```r
dynr_initial <- dynr::prep.initial(
  values.inistate = c(0, 0, 0),
  params.inistate = c("mu0_1", "mu0_2", "mu0_3"),
  values.inicov = diag(3),
  params.inicov = matrix(
    data = c(
      "sigma0_11", "sigma0_12", "sigma0_13",
      "sigma0_12", "sigma0_22", "sigma0_23",
      "sigma0_13", "sigma0_23", "sigma0_33"
    ),
    nrow = 3
  )
)
```

### Prepare Measurement Model


```r
dynr_measurement <- dynr::prep.measurement(
  values.load = diag(3),
  params.load = matrix(data = "fixed", nrow = 3, ncol = 3),
  state.names = c("eta_1", "eta_2", "eta_3"),
  obs.names = c("y1", "y2", "y3")
)
```

### Prepare Dynamic Process


```r
dynr_dynamics <- dynr::prep.formulaDynamics(
  formula = list(
    eta_1 ~ alpha_1 * 1 + beta_11 * eta_1 + beta_12 * eta_2 + beta_13 * eta_3,
    eta_2 ~ alpha_2 * 1 + beta_21 * eta_1 + beta_22 * eta_2 + beta_23 * eta_3,
    eta_3 ~ alpha_3 * 1 + beta_31 * eta_1 + beta_32 * eta_2 + beta_33 * eta_3
  ),
  startval = c(
    alpha_1 = 0, alpha_2 = 0, alpha_3 = 0,
    beta_11 = 0, beta_12 = 0, beta_13 = 0,
    beta_21 = 0, beta_22 = 0, beta_23 = 0,
    beta_31 = 0, beta_32 = 0, beta_33 = 0
  ),
  isContinuousTime = FALSE
)
```

### Prepare Process Noise


```r
dynr_noise <- dynr::prep.noise(
  values.latent = diag(3),
  params.latent = matrix(
    data = c(
      "psi_11", "psi_12", "psi_13",
      "psi_12", "psi_22", "psi_23",
      "psi_13", "psi_23", "psi_33"
    ),
    nrow = 3
  ),
  values.observed = matrix(data = 0, nrow = 3, ncol = 3),
  params.observed = matrix(data = "fixed", nrow = 3, ncol = 3)
)
```

### Prepare the Model


```r
model <- dynr::dynr.model(
  data = dynr_data,
  initial = dynr_initial,
  measurement = dynr_measurement,
  dynamics = dynr_dynamics,
  noise = dynr_noise,
  outfile = "var.c"
)
```



### Fit the Model


```r
results <- dynr::dynr.cook(
  model,
  debug_flag = TRUE,
  verbose = FALSE
)
```

```
## [1] "Get ready!!!!"
## using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
## Optimization function called.
## Starting Hessian calculation ...
## Finished Hessian calculation.
## Original exit flag:  3 
## Modified exit flag:  3 
## Optimization terminated successfully: ftol_rel or ftol_abs was reached. 
## Original fitted parameters:  0.003911589 0.002690734 0.005778407 0.6885433 
## 0.00896143 -0.01172181 0.4916282 0.6053229 0.0001750519 -0.1013145 0.4054041 
## 0.4992474 -0.00473419 -0.004954486 0.003974128 -0.01524407 0.004266951 
## 0.003887481 -0.05617529 0.1212663 0.1306726 0.1918628 0.1357277 -0.08446735 
## 0.03990803 -0.1619475 0.3552519 
## 
## Transformed fitted parameters:  0.003911589 0.002690734 0.005778407 0.6885433 
## 0.00896143 -0.01172181 0.4916282 0.6053229 0.0001750519 -0.1013145 0.4054041 
## 0.4992474 0.995277 -0.004931086 0.003955358 0.984896 0.004182802 1.003929 
## -0.05617529 0.1212663 0.1306726 1.211504 0.1644347 -0.1023326 1.063033 
## -0.1824306 1.462478 
## 
## Doing end processing
## Successful trial
## Total Time: 11.95532 
## Backend Time: 11.94808
```

## Summary


```r
summary(results)
```

```
## Coefficients:
##             Estimate Std. Error t value   ci.lower   ci.upper Pr(>|t|)    
## alpha_1    0.0039116  0.0070577   0.554 -0.0099212  0.0177444   0.2897    
## alpha_2    0.0026907  0.0070221   0.383 -0.0110723  0.0164538   0.3508    
## alpha_3    0.0057784  0.0070890   0.815 -0.0081158  0.0196726   0.2075    
## beta_11    0.6885433  0.0057281 120.204  0.6773164  0.6997702   <2e-16 ***
## beta_12    0.0089614  0.0048365   1.853 -0.0005179  0.0184408   0.0320 *  
## beta_13   -0.0117218  0.0048821  -2.401 -0.0212906 -0.0021531   0.0082 ** 
## beta_21    0.4916282  0.0056974  86.290  0.4804615  0.5027949   <2e-16 ***
## beta_22    0.6053229  0.0048102 125.842  0.5958952  0.6147507   <2e-16 ***
## beta_23    0.0001751  0.0048567   0.036 -0.0093440  0.0096941   0.4856    
## beta_31   -0.1013145  0.0057530 -17.611 -0.1125901 -0.0900389   <2e-16 ***
## beta_32    0.4054041  0.0048572  83.464  0.3958842  0.4149241   <2e-16 ***
## beta_33    0.4992474  0.0049034 101.816  0.4896368  0.5088580   <2e-16 ***
## psi_11     0.9952770  0.0099581  99.946  0.9757594  1.0147946   <2e-16 ***
## psi_12    -0.0049311  0.0070028  -0.704 -0.0186563  0.0087941   0.2407    
## psi_13     0.0039554  0.0070728   0.559 -0.0099070  0.0178177   0.2880    
## psi_22     0.9848960  0.0098490  99.999  0.9655922  1.0041997   <2e-16 ***
## psi_23     0.0041828  0.0070357   0.595 -0.0096068  0.0179724   0.2761    
## psi_33     1.0039287  0.0100415  99.978  0.9842478  1.0236096   <2e-16 ***
## mu0_1     -0.0561753  0.2452630  -0.229 -0.5368819  0.4245313   0.4094    
## mu0_2      0.1212663  0.2285617   0.531 -0.3267065  0.5692391   0.2979    
## mu0_3      0.1306726  0.2710392   0.482 -0.4005544  0.6618996   0.3149    
## sigma0_11  1.2115043  0.3926885   3.085  0.4418489  1.9811596   0.0010 ***
## sigma0_12  0.1644347  0.2552730   0.644 -0.3358911  0.6647605   0.2597    
## sigma0_13 -0.1023326  0.2993281  -0.342 -0.6890049  0.4843398   0.3662    
## sigma0_22  1.0630334  0.3397533   3.129  0.3971292  1.7289376   0.0009 ***
## sigma0_23 -0.1824306  0.2825020  -0.646 -0.7361243  0.3712632   0.2592    
## sigma0_33  1.4624785  0.4589310   3.187  0.5629902  2.3619668   0.0007 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## -2 log-likelihood value at convergence = 169965.97
## AIC = 170019.97
## BIC = 170233.37
```



### Estimated Coefficients


```r
alpha_hat
```

```
## [1] 0.003911589 0.002690734 0.005778407
```

```r
beta_hat
```

```
##            [,1]       [,2]          [,3]
## [1,]  0.6885433 0.00896143 -0.0117218102
## [2,]  0.4916282 0.60532294  0.0001750519
## [3,] -0.1013145 0.40540413  0.4992474039
```

```r
psi_hat
```

```
##              [,1]         [,2]        [,3]
## [1,]  0.995276998 -0.004931086 0.003955358
## [2,] -0.004931086  0.984895965 0.004182802
## [3,]  0.003955358  0.004182802 1.003928697
```

```r
mu0_hat
```

```
## [1] -0.05617529  0.12126629  0.13067261
```

```r
sigma0_hat
```

```
##            [,1]       [,2]       [,3]
## [1,]  1.2115043  0.1644347 -0.1023326
## [2,]  0.1644347  1.0630334 -0.1824306
## [3,] -0.1023326 -0.1824306  1.4624785
```

### Discrepancy Between Estimated and Population Coefficients


```r
abs(alpha - alpha_hat)
```

```
## [1] 0.003911589 0.002690734 0.005778407
```

```r
abs(beta - beta_hat)
```

```
##             [,1]        [,2]         [,3]
## [1,] 0.011456696 0.008961430 0.0117218102
## [2,] 0.008371798 0.005322944 0.0001750519
## [3,] 0.001314504 0.005404135 0.0007525961
```

```r
abs(psi - psi_hat)
```

```
##             [,1]        [,2]        [,3]
## [1,] 0.004723002 0.004931086 0.003955358
## [2,] 0.004931086 0.015104035 0.004182802
## [3,] 0.003955358 0.004182802 0.003928697
```



## References
